# API Gateway REST API in front of the Lambda. REST (v1) rather than HTTP
# (v2) deliberately: it has native API keys and usage plans, so the auth
# gate, throttling, and monthly quota are all enforced at the gateway with
# zero custom code, before any Lambda ever runs.

resource "aws_api_gateway_rest_api" "mcp" {
  name        = "bbb-mcp"
  description = "Auth-gated public MCP endpoint for Brisbane Bowser Beater"

  endpoint_configuration {
    types = ["REGIONAL"]
  }
}

resource "aws_api_gateway_resource" "mcp" {
  rest_api_id = aws_api_gateway_rest_api.mcp.id
  parent_id   = aws_api_gateway_rest_api.mcp.root_resource_id
  path_part   = "mcp"
}

# Only POST /mcp exists. Streamable-HTTP MCP in stateless mode needs nothing
# else, and the gateway rejects every other method/path before the Lambda
# (the handler's own 405 guard is second-layer defense).
resource "aws_api_gateway_method" "mcp_post" {
  rest_api_id      = aws_api_gateway_rest_api.mcp.id
  resource_id      = aws_api_gateway_resource.mcp.id
  http_method      = "POST"
  authorization    = "NONE"
  api_key_required = true
}

resource "aws_api_gateway_integration" "mcp_post" {
  rest_api_id             = aws_api_gateway_rest_api.mcp.id
  resource_id             = aws_api_gateway_resource.mcp.id
  http_method             = aws_api_gateway_method.mcp_post.http_method
  integration_http_method = "POST"
  type                    = "AWS_PROXY"
  uri                     = aws_lambda_function.server.invoke_arn
}

resource "aws_lambda_permission" "apigw" {
  statement_id  = "AllowBbbMcpApiInvoke"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.server.function_name
  principal     = "apigateway.amazonaws.com"
  # Only POST /mcp on this specific API/stage may invoke the function.
  source_arn = "${aws_api_gateway_rest_api.mcp.execution_arn}/*/POST/mcp"
}

resource "aws_api_gateway_deployment" "mcp" {
  rest_api_id = aws_api_gateway_rest_api.mcp.id

  # Redeploy whenever any part of the API surface changes.
  triggers = {
    redeployment = sha1(jsonencode([
      aws_api_gateway_resource.mcp.id,
      aws_api_gateway_method.mcp_post.id,
      aws_api_gateway_method.mcp_post.api_key_required,
      aws_api_gateway_integration.mcp_post.id,
      aws_api_gateway_integration.mcp_post.uri,
    ]))
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_api_gateway_stage" "prod" {
  rest_api_id   = aws_api_gateway_rest_api.mcp.id
  deployment_id = aws_api_gateway_deployment.mcp.id
  stage_name    = "prod"
}

# The auth gate: callers present this key as the x-api-key header. The value
# is generated by AWS, lives only in AWS, and is never output by Terraform
# or printed in workflow logs; the operator retrieves it via CloudShell
# (see infra/BOOTSTRAP.md).
resource "aws_api_gateway_api_key" "mcp" {
  name        = "bbb-mcp-key"
  description = "Access key for the BBB MCP endpoint"
}

resource "aws_api_gateway_usage_plan" "mcp" {
  name        = "bbb-mcp-usage-plan"
  description = "Throttle and monthly quota for the BBB MCP endpoint"

  api_stages {
    api_id = aws_api_gateway_rest_api.mcp.id
    stage  = aws_api_gateway_stage.prod.stage_name
  }

  throttle_settings {
    rate_limit  = var.throttle_rate_limit
    burst_limit = var.throttle_burst_limit
  }

  quota_settings {
    limit  = var.monthly_quota
    period = "MONTH"
  }
}

resource "aws_api_gateway_usage_plan_key" "mcp" {
  key_id        = aws_api_gateway_api_key.mcp.id
  key_type      = "API_KEY"
  usage_plan_id = aws_api_gateway_usage_plan.mcp.id
}
